# Generated by Django 5.2.12 on 2026-09-24 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_storeprofile_ai_subscription_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='location_place_name',
            field=models.CharField(blank=True, help_text='Reverse-geocoded "City, State" for location_latitude/longitude, resolved once when captured.', max_length=255),
        ),
        migrations.CreateModel(
            name='ProviderAPICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(db_index=True, help_text='The Django settings attribute this overrides, e.g. NVIDIA_LUNA_API_KEY.', max_length=80, unique=True)),
                ('value', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider API Credential',
                'verbose_name_plural': 'Provider API Credentials',
            },
        ),
    ]
