# Generated by Django 5.2.12 on 2026-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_provider_api_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='youtube_cookies_txt',
            field=models.TextField(blank=True, help_text='Paste a YouTube cookies.txt (Netscape format), exported while logged into YouTube in a normal browser — fixes "Sign in to confirm you\'re not a bot" download failures, which datacenter/server IPs (like most hosting providers) hit far more than a home connection. Leave blank to disable. Superadmin-only feature — see myapp.youtube_download.'),
        ),
    ]
