# Generated by Django 5.2.12 on 2026-09-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_site_customization_youtube_cookies'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='site_disabled',
            field=models.BooleanField(default=False, help_text='Shows a bare 404 "Site Not Found" page to every visitor instead of the real site. The dashboard itself (and /admin/) stays reachable so staff can always log in and switch this back off — see myapp.middleware.SiteDisabledMiddleware.'),
        ),
    ]
