# Generated by Django 5.2.12 on 2026-09-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_site_customization_site_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecustomization',
            name='support_email',
            field=models.EmailField(default='support@edutrellis.in', help_text='Shown in the in-app "Contact support" popup\'s email option and used for its mailto: link.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitecustomization',
            name='support_whatsapp_number',
            field=models.CharField(default='9695953183', help_text='Shown in the in-app "Contact support" popup\'s WhatsApp option, exactly as typed. Also used to build its wa.me link — with or without a country code both work.', max_length=20),
        ),
    ]
