# Generated by Django 5.2.12 on 2026-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_aimodelcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelcontrol',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='aimodelcontrol',
            name='display_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
