# Generated by Django 5.2.12 on 2026-10-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_aimodelcontrol_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
    ]
