# Generated by Django 5.2.12 on 2026-10-03 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_aicodingkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicodingkey',
            name='label',
            field=models.CharField(blank=True, help_text='Empty for the manual key; otherwise the computer it was set up on.', max_length=60),
        ),
        migrations.AlterField(
            model_name='aicodingkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coding_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AICodingDeviceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_hash', models.CharField(max_length=64, unique=True)),
                ('user_code', models.CharField(db_index=True, max_length=9, unique=True)),
                ('machine', models.CharField(blank=True, max_length=60)),
                ('requester_ip', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Coding Device Code',
                'verbose_name_plural': 'AI Coding Device Codes',
            },
        ),
    ]
