# Generated by Django 5.2.12 on 2026-10-03 22:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_remove_deleted_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICodingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(blank=True, help_text='The computer the key was set up on; empty for the manual key.', max_length=60)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='myapp.aicodingkey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenCode Session',
                'verbose_name_plural': 'OpenCode Sessions',
                'ordering': ['-last_request_at'],
            },
        ),
        migrations.CreateModel(
            name='AICodingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('stream', models.BooleanField(default=False)),
                ('trigger', models.CharField(default='user', help_text='Role of the newest message: user, or tool for a tool result.', max_length=10)),
                ('user_text', models.TextField(blank=True)),
                ('reply_text', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('reply_chars', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coding_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='myapp.aicodingsession')),
            ],
            options={
                'verbose_name': 'OpenCode Request',
                'verbose_name_plural': 'OpenCode Requests',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(blank=True, max_length=60)),
                ('language', models.CharField(blank=True, max_length=12)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('turn_count', models.PositiveIntegerField(default=0, help_text='How many things the caller said.')),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('audio', models.FileField(blank=True, max_length=200, upload_to='ai_calls/')),
                ('audio_mime', models.CharField(blank=True, max_length=60)),
                ('audio_bytes', models.PositiveBigIntegerField(default=0)),
                ('audio_chunks', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='myapp.aiconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Voice Call',
                'verbose_name_plural': 'AI Voice Calls',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='myapp_aical_user_id_f909dc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aicodingsession',
            index=models.Index(fields=['user', '-last_request_at'], name='myapp_aicod_user_id_a5aabb_idx'),
        ),
        migrations.AddConstraint(
            model_name='aicodingsession',
            constraint=models.UniqueConstraint(fields=('user', 'fingerprint'), name='uniq_coding_session_per_user_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='aicodingrequest',
            index=models.Index(fields=['user', '-created_at'], name='myapp_aicod_user_id_48cb31_idx'),
        ),
    ]
