# Generated by Django 5.2.12 on 2026-10-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_default_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimessage',
            name='reply_to_text',
            field=models.TextField(blank=True),
        ),
    ]
