# Generated by Django 5.2.12 on 2026-10-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_aimessage_reply_to_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_type', models.CharField(choices=[('nvidia', 'NVIDIA NIM (build.nvidia.com)'), ('openai', 'Other OpenAI-compatible API')], default='nvidia', max_length=10)),
                ('base_url', models.URLField(blank=True, help_text='Only for an OpenAI-compatible API; NVIDIA uses its own.', max_length=300)),
                ('model_id', models.CharField(help_text="The provider's model name, e.g. nvidia/nemotron-3-super-120b-a12b.", max_length=200)),
                ('display_name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('thinking_control', models.BooleanField(default=False, help_text='Accepts the "no visible thinking" switch NVIDIA reasoning models use.')),
                ('vision', models.BooleanField(default=False, help_text='Can read attached images.')),
                ('check_report', models.JSONField(blank=True, default=list)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Added AI Model',
                'verbose_name_plural': 'Added AI Models',
                'ordering': ['created_at'],
            },
        ),
    ]
