# Generated by Django 5.2.12 on 2026-10-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_customaimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelcontrol',
            name='identity_creator',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aimodelcontrol',
            name='identity_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aimodelcontrol',
            name='identity_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='aimodelcontrol',
            name='identity_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='aimodelcontrol',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
