# Generated by Django 5.2.12 on 2026-10-08 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_model_removal_and_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.CharField(max_length=300)),
                ('key_status', models.CharField(blank=True, max_length=20)),
                ('key_detail', models.CharField(blank=True, max_length=300)),
                ('key_seconds', models.FloatField(blank=True, null=True)),
                ('key_model', models.CharField(blank=True, max_length=200)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('models_snapshot', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Checker Run',
                'verbose_name_plural': 'API Checker Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APICheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('seconds', models.FloatField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('reply', models.CharField(blank=True, max_length=200)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='myapp.apicheckrun')),
            ],
            options={
                'verbose_name': 'API Checker Result',
                'verbose_name_plural': 'API Checker Results',
                'ordering': ['tested_at'],
            },
        ),
    ]
